name: "Update known versions"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # Run every day at 4am UTC
  repository_dispatch:
    types: [ pypi_release ]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: true
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "20"
      - name: Update known versions
        id: update-known-versions
        run:
          node dist/update-known-versions/index.js
          src/download/checksum/known-checksums.ts
          version-manifest.json
          ${{ secrets.GITHUB_TOKEN }}
      - name: Check for changes
        id: changes-exist
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
              echo "changes-exist=true" >> "$GITHUB_OUTPUT"
          else
              echo "changes-exist=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Compile changes
        if: ${{ steps.changes-exist.outputs.changes-exist == 'true' }}
        run: npm ci --ignore-scripts && npm run all
      - name: Commit and push changes
        if: ${{ steps.changes-exist.outputs.changes-exist == 'true' }}
        id: commit-and-push
        continue-on-error: true
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "chore: update known versions for $LATEST_VERSION"
          git push origin HEAD:refs/heads/main
        env:
          LATEST_VERSION: ${{ steps.update-known-versions.outputs.latest-version }}

      - name: Create Pull Request
        if: ${{ steps.changes-exist.outputs.changes-exist == 'true' && steps.commit-and-push.outcome != 'success' }}
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          commit-message: "chore: update known checksums"
          title:
            "chore: update known checksums for ${{
            steps.update-known-versions.outputs.latest-version }}"
          body:
            "chore: update known checksums for ${{
            steps.update-known-versions.outputs.latest-version }}"
          base: main
          labels: "automated-pr,update-known-versions"
          branch: update-known-versions-pr
          delete-branch: true
