---
name: Update Major Minor Tags

# yamllint disable-line rule:truthy
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  update_major_minor_tags:
    name: Make sure major and minor tags are up to date on a patch release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Update semver
        uses: haya14busa/action-update-semver@v1.2.1