name: "Update known checksums"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Update known checksums
        id: update-known-checksums
        run:
          node dist/update-known-checksums/index.js
          src/download/checksum/known-checksums.ts ${{ secrets.GITHUB_TOKEN }}
      - run: npm install && npm run all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          commit-message: "chore: update known checksums"
          title:
            "chore: update known checksums for ${{
            steps.update-known-checksums.outputs.latest-version }}"
          body:
            "chore: update known checksums for ${{
            steps.update-known-checksums.outputs.latest-version }}"
          base: main
          labels: "automated-pr,update-known-checksums"
          branch: update-known-checksums-pr
          delete-branch: true
